version: '3.2'

services:

  cache:
    image: ${CONTAINER_CACHE_VERSION}
    container_name: ${CONTAINER_CACHE_NAME}
    restart: unless-stopped
    env_file: .app.env
    depends_on:
     - app
    ports:
     - 127.0.0.1:${CONTAINER_CACHE_PORT}:80
    networks:
      internal_net:
        ipv4_address: 172.168.10.9
