version: '3.2'

services:

  app:
    image: ${CONTAINER_APP_VERSION}
    container_name: ${CONTAINER_APP_NAME}
    restart: unless-stopped
    env_file: .app.env
    volumes:
      - ./var/default/drupal-hash-salt.txt:/data/drupal-hash-salt-default.txt
      - ./var/default/files:/usr/share/nginx/html/web/sites/default/files
#    ports:
#      - 127.0.0.1:${CONTAINER_APP_PORT}:80
