version: '3.2'

services:

  cache:
    image: ${CONTAINER_CACHE_VERSION}
    container_name: ${CONTAINER_CACHE_NAME}
    restart: unless-stopped
    env_file: .app.env
    depends_on:
      - app
    ports:
      - 127.0.0.1:${CONTAINER_CACHE_PORT}:80

  app:
    image: ${CONTAINER_APP_VERSION}
    container_name: ${CONTAINER_APP_NAME}
    restart: unless-stopped
    env_file: .app.env
    volumes:
      - ./var/default/drupal-hash-salt.txt:/data/drupal-hash-salt-default.txt
      - ./var/default/files:/usr/share/nginx/html/web/sites/default/files

  memcached:
    image: ${CONTAINER_MEMCACHED_VERSION}
    container_name: ${CONTAINER_MEMCACHED_NAME}
    restart: unless-stopped
    env_file: .app.env
    depends_on:
      - app

  db:
    image: ${CONTAINER_DB_VERSION}
    container_name: ${CONTAINER_DB_NAME}
    restart: unless-stopped
    env_file: .app.env
