version: '3.2'

services:

  memcached:
    image: ${CONTAINER_MEMCACHED_VERSION}
    container_name: ${CONTAINER_MEMCACHED_NAME}
    restart: unless-stopped
    depends_on:
      - app
#    networks:
#      internal_net:
#        ipv4_address: 172.168.10.12
